name: Build on Linux with VCPKG

on:
  push:
    branches: [ "devel", "main" ]
  pull_request:
    branches: [ "devel", "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: VCPKG Build
      uses: johnwason/vcpkg-action@v8
      id: vcpkg
      with:
        pkgs: zlib sonivox
        triplet: x64-linux-release
        token: ${{ github.token }}      

    - name: Configure CMake
      run: cmake  ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -B ${{github.workspace}}/build
        -DFIND_SONIVOX=ON
        -Dsonivox_SHARED_LIBS=OFF
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
